package locators;

public interface EMS_Contract_Billing_Generation_And_Verification_Locatros extends EMS_Contract_Billing_Generation{
	public static String P_Contract_Module = "Contract_Module >//div[@id='nfr_topbar_autocomp_panel']//span[contains(text(),'EMS Contract Billing Generation and Verification')]";
	public static String P_New_Btn = "New_Btn >//button[contains(@id,'btnTblNew')]";
	public static String P_Contract_Module_Page = "Contract_Module_Page >(//label[contains(text(),'EMS Contract Billing Generation and Verification')])[1]";
	public static String P_Contact_No_Plus_Btn = "Contact_No_Plus_Btn >(//fieldset[contains(@id,'EDB-EDB_ContractNo')]//following::button)[1]";
	public static String P_Search_Contract_No_Popup = "Search_Contact_No_Popup >//span[contains(@id,'nfr_sch_multicolumn_title')]//label";
	public static String P_Search_Contract_No_Popup_SelBtn = "Search_Contact_No_Popup_SelBtn >//span[contains(@id,'nfr_sch_multicolumn_title')]//following::button[contains(@id,'multicol_okbtn')]";
	public static String P_Search_Contract_Alert_Popup = "Search_Contact_Alert_Popup >//div[contains(@id,'primefacesmessagedlg')]//span[text()='Search Contract No']";
	public static String P_Search_Contract_Alert_Msg = "Search_Contact_Alert_Msg >//span[contains(text(),'Search Contract No')]//following::div[1]";
	public static String P_Search_Contract_Alert_Close = "Search_Contact_Alert_Close >(//span[contains(text(),'Search Contract No')]//following::a//span)[1]";
	public static String P_Search_Contract_No_Popup_Close = "Search_Contact_No_Popup_Close >(//span[contains(@id,'nfr_sch_multicolumn_title')]//following::a//span)[1]";
	public static String P_Cancel_Btn = "Cancel_Btn >//button[contains(@id,'btnTblCancel')]";
	public static String P_Incorrect_Password_Popup = "Incorrect_Password_Popup>//div[@id='lrp_cust_growl_container']//p";
	public static String P_Authentication_popup = "Authentication_popup>//span[contains(@id,'authentication_popup_title')]";
	public static String P_Authentication_popup_TxtField = "Authentication_popup_TxtField >//input[contains(@id,'pwd_authenticate-EDB_Password')]";
	public static String P_Authentication_popup_Close = "Authentication_popup_Close >(//span[contains(@id,'authentication_popup_title')]//following::a)[1]";
	public static String P_Authentication_popup_OkBtn = "Authentication_popup_OkBtn >(//span[contains(@id,'authentication_popup_title')]//following::span[text()='OK'])[1]";
	public static String P_Search_Contract_No_TxtField = "Search_Contract_No_TxtField >//div[@id='nfr-multi-div']//input[@aria-label='Contract No. Filter Input']";
	public static String P_Enter_Password_Popup = "Enter_Password_Popup >//div[@id='lrp_cust_growl_container']//p";
	public static String P_Bill_Period_Month_DD = "P_Bill_Period_Month_DD >//label[@id='EDB-EDB_cmbPeriod_label']";
	public static String P_Bill_Period_Year_Field = "P_Bill_Period_Year_Field >//input[contains(@id,'EDB_spinneryear')]";
	public static String P_Verification_Popup_NoBtn = "P_Verification_Popup_NoBtn >//h2[text()='EMS Contract Billing Generation and Verification']//following::button[text()='No']";
	public static String P_Verification_Popup = "Verification_Popup >//h2[text()='EMS Contract Billing Generation and Verification']//following::span[2]";
	public static String P_Verification_Popup_YesBtn = "Verification_Popup_YesBtn >//h2[text()='EMS Contract Billing Generation and Verification']//following::button[text()='Yes']";
	public static String P_Bills_Generated_Popup = "Bills_Generated_Popup >//*[contains(text(),'Bills Successfully Generated')]";
	public static String P_Genarate_Bills_Btn = "Genarate_Bills_Btn >//button[@id='EDB-EDB_GenBill']";
	public static String P_EMS_Cancel_Btn = "EMS_Cancel_Btn >(//label[contains(text(),'EMS Contract Billing Generation and Verification ')]//following::a)[3]";
	public static String P_Show_Bills_Btn = "Show_Bills_Btn >//button[@id='EDB-EDB_ShowBill']";
	public static String P_Sel_ContNo_Popup = "New_Btn >//*[text()='Select a Contract No.']";
	public static String P_Verify_Btn = "Verify_Btn >//button[@id='EDB-EDB_VerifyBill']";
	public static String P_Contract_No_CheckBox_Btn = "Contract_No_CheckBox_Btn >//tbody[@id='EDB-EDB_summayDetailTreeTable_data']//following::div[contains(@id,'summayDetailTreeTable')]//div[2]";
	public static String P_Verified_Popup = "Verified_Popup >//*[text()='Verified Successfully']";
	public static String P_Remark_Txt_Field = "Remark_Txt_Field >//textarea[contains(@id,'EDB_popupVerifyRemarks')]";
	public static String P_Remark_Ok_Btn = "Remark_Ok_Btn >//button[contains(@id,'RemarksOk')]";
	public static String P_Highlighted_Color = "Highlighted_Color >(//tbody[@id='EDB-EDB_summayDetailTreeTable_data']//following::tr)[1]";
	public static String P_ApproveBill_Btn = "ApproveBill_Btn >//button[contains(@id,'ApproveBill')]";
	public static String P_ReGenerate_Btn = "ReGenerate_Btn >//button[contains(@id,'ReGenBill')]";
	public static String P_Reset_Btn = "Reset_Btn >//button[contains(@id,'buttonReset')]";
	public static String P_Regenaration_Pass_TxtField = "Regenaration_Pass_Popup >(//input[contains(@id,'Password')])";
	public static String P_Regenaration_Pass_OkBtn = "Regenaration_Pass_OkBtn >(//input[contains(@id,'Password')])//following::button[1]";
	public static String P_Regenaration_Pass_Close = "Regenaration_Pass_Close >(//input[contains(@id,'Password')])//preceding::a[1]";
	public static String P_Bill_Run_Status_okBtn = "Bill_Run_Status_okBtn >(//span[contains(@id,'EDB_BillRunStatusShow_title')]//following::span[contains(text(),'OK')])[1]";
	public static String P_Bill_Not_Verify_Msg = "Bill_Not_Verify_Msg >(//span[text()='Message'])[1]//following::td[4]";
	public static String P_Bill_Generated_Msg = "Bill_Not_Verify_Msg >(//span[text()='Bill Run Message'])[1]//following::td[4]";
	public static String P_Apporved_Popup = "Apporved_Popup >//*[text()='Approved Successfully']";
	public static String P_Approve_Remarks_TxtFiled = "Approve_Remarks_TxtFiled >//textarea[contains(@id,'EDB_popupapproveRemarks')]";
	public static String P_Approve_Remarks_OkBtn = "Approve_Remarks_OkBtn >//button[contains(@id,'approveRemarksOk')]";
	public static String P_Enter_Approve_Remark_Popup = "Enter_Approve_Remark_Popup >//div[@id='lrp_cust_growl_container']//p";
	public static String Bill_Yes_Btn = "Bill_Yes_Btn >//button[@id='EDB_BillReGenCnfFrm-EDB_BillReGenCnfDT-EDB_BillReGenApp']";
	public static String month_Select = "month_Select>//li[text()='%s']";
	public static String element = "element>//div[text()='%s']";
	public static String generatebutton = "button>//span[text()='%s']";
	public static String ContractNo_Select_CheckBox ="ContractNo_Select_CheckBox>//td[text()='%s']//preceding::td[text()='Total by Contract']//preceding::div[contains(@class,'chkbox')][1]";
	public static String verrified_Row ="verrified_Column>//td[text()='%s']//preceding::td[text()='Total by Contract']//ancestor::tr[1]";
	public static String contrac_No = "contrac_No>//div[@id='nfr-multi-div']//div[text()='%s']";
	public static String P_Approve_Remark_Title="Approve_Remark_Title >(//div[contains(@id,'EDB_approveRemarks_popup')]//span)[1]";
	public static String P_Add_Remark_Title="Add_Remark_Title >(//div[contains(@id,'EDB_verifyRemarks_popup')]//span)[1]";
	public static String P_Enter_Verify_Remark_Popup = "Enter_Verify_Remark_Popup >//div[@id='lrp_cust_growl_container']//p";
	public static String P_Invalid_Terms_Popup_Msg = "Invalid_Terms_Popup_Msg >(//span[text()='Message'])[1]//following::td[7]";
	public static String P_Invalid_Terms_Popup_YesBtn = "Invalid_Terms_Popup_YesBtn >(//span[text()='Message'])[1]//following::span[text()='Yes']";
	public static String P_Before_ReGen_ContractNo_Value = "Before_ReGen_ContractNo_Value >//div[contains(@id,'ContractNoSelectMenu')]//li";
	public static String P_After_ReGen_ContractNo_Value = "After_ReGen_ContractNo_Value >//div[contains(@id,'ContractNoSelectMenu')]";
	public static String P_Invalid_Terms_Popup_Close = "Invalid_Terms_Popup_Close >(//span[@id='EDB_BillPaytermNotValid_title']//following::a)[1]";
	public static String P_Verify_Remark_Close = "Verify_Remark_Close >//span[contains(@id,'EDB_verifyRemarks_popup_title')]//following::a[1]";
	public static String P_Approve_Remark_Close = "Approve_Remark_Close >//span[contains(@id,'EDB_approveRemarks_popup_title')]//following::a[1]";
	public static String P_Missng_Bill_Msg = "Missng_Bill_Msg >//span[@id='EDB_MissingBillPeriod_title']//following::span[text()='Message'][1]//following::td[6]";
	public static String P_Missng_Bill_CloseBtn = "Missng_Bill_CloseBtn >//span[@id='EDB_MissingBillPeriod_title']//following::a[1]";
	public static String P_Bill_Already_Exist_Popup_Msg = "Bill_Already_Exist_Popup_Msg >//span[@id='EDB_Regencheck_title']//following::td[3]";
	public static String P_Bill_Already_Exist_Popup_close = "Bill_Already_Exist_Popup_Close >//span[@id='EDB_Regencheck_title']//following::a[1]";
	public static String P_Bill_Already_Exist_Popup_OkBtn = "Bill_Already_Exist_Popup_OkBtn >//span[@id='EDB_Regencheck_title']//following::span[text()='Ok']";
	public static String P_Bill_Already_Exist_Popup_NoBtn = "Bill_Already_Exist_Popup_NoBtn >//span[@id='EDB_Regencheck_title']//following::span[text()='No']";
	public static String P_Upload_Gate_Module = "Upload_Gate_Module >(//label[text()='Bill Upload Gate'])[1]";
	public static String P_Service_Must_Enter_Popup = "Service_Must_Enter_Popup >//*[text()='Service must be entered']";
	public static String P_Vessel_Must_Enter_Popup = "Vessel_Must_Enter_Popup >//*[text()='Vessel must be entered']";
	public static String P_Voyage_Must_Enter_Popup = "Voyage_Must_Enter_Popup >//*[text()='Voyage must be entered']";
	public static String P_Bound_Must_Select_Popup = "Bound_Must_Select_Popup >//*[text()='Bound must be selected']";
	public static String P_Service_Txt_Field = "Service_Txt_Field >//input[contains(@id,'txtSinService')]";
	public static String P_Vessel_Txt_Field = "Vessel_Txt_Field >//input[contains(@id,'txtSinVslCode')]";
	public static String P_Voyage_Txt_Field = "Voyage_Txt_Field >//input[contains(@id,'txtSinVoyage')]";
	public static String P_Bound_Txt_Field = "Bound_Txt_Field >//input[contains(@id,'txtSinBound')]";
	public static String P_POL_Txt_Field = "POL_Txt_Field >//input[contains(@id,'txtSinPOL_input')]";
	public static String P_POL_Must_Select_Popup = "POL_Must_Select_Popup >//*[text()='POL must be entered']";
	public static String P_Invalid_Activity_Date_Popup = "Invalid_Activity_Date_Popup >(//div[contains(@id,'errDetList')]//following::td[text()='DA']//following::td)[1]";
	public static String P_Invalid_Service_Popup = "Invalid_Service_Popup >(//div[contains(@id,'errDetList')]//following::td[text()='IS']//following::td)[1]";
	public static String P_Invalid_Terminal_Popup = "Invalid_Terminal_Popup >(//div[contains(@id,'errDetList')]//following::td[text()='IT']//following::td)[1]";
	public static String P_Invalid_Bound_Popup = "Invalid_Bound_Popup >(//div[contains(@id,'errDetList')]//following::td[text()='BO']//following::td)[1]";
	public static String P_Invalid_Voyage_Popup = "Invalid_Voyage_Popup >(//div[contains(@id,'errDetList')]//following::td[text()='VO']//following::td)[1]";
	public static String P_Invalid_POD_Popup = "Invalid_POD_Popup >(//div[contains(@id,'errDetList')]//following::td[text()='AG']//following::td)[1]";
	public static String P_Bill_Upload_Gate_Cancel_Btn = "Enq_His_Cancel_Btn >(//label[contains(text(),'Bill Upload Gate')])[1]//following::a[3]";
	public static String P_Lesser_Bill_Cancel_Btn = "Enq_His_Cancel_Btn >(//label[contains(text(),'Lessor Bill Upload')])[1]//following::a[3]";
	public static String P_Bill_Already_Exist_Popup_YesBtn = "Bill_Already_Exist_Popup_OkBtn >//button[@id='EDB_RegencheckForm-EDB_RegencheckformDataGrid-EDB_RegencheckcmdBtnOk']";
	public static String from_Date="from_Date>//input[@id='BUG-BUG_fromDate_input']";
	public static String to_Date="to_Date>//input[@id='BUG-BUG_toDate_input']";
	public static String close_Tab = "close_Tab>(//a[contains(@id,'img3')]/child::i[@class='fa fa-remove mdlclose'])[1]";

}
